version: '3.8'

services:
  web:
    image: codebyte:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./codebyte.sql:/docker-entrypoint-initdb.d/codebyte.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  redis:
      image: redis:7-alpine
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - app-net

volumes:
  mysql_data:
  redis_data:
networks:
  app-net:
    name: code-byte-app-net