apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-byte-production-secrets
  namespace: code-byte-ns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-env-secret
  dataFrom:
  - extract:
      key: production/code-byte